import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import React from 'react';

import { AppProviders } from '@/components/providers';
import '@/app/global.css';
import { Footer } from '@/components/ui/layouts/Footer';
import { Header } from '@/components/ui/layouts/Header';
import { MainContent } from '@/components/ui/layouts/MainContent';

export const runtime = 'edge';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} as const;

type Props = {
  children: React.ReactNode;
};

const RootLayout: React.FC<Props> = ({ children }) => {
  return (
    <html lang="ja">
      {/* <body className={inter.className}>{children}</body> */}
      <body>
        <AppProviders>
          <Header />
          <MainContent>{children}</MainContent>
          <Footer />
        </AppProviders>
      </body>
    </html>
  );
};

export default RootLayout;
